name: Markdown Interpolation Action
author: Austen Stone
description: Interpolate markdown files with variables
branding:
  icon: "file-text"
  color: "orange"

inputs:
  files-regex:
    description: Names of files to modify regex match.
    default: README.md
    required: false
  files-regex-flags:
    description: Regex flags for files-regex match.
    default: 'gi'
    required: false
  values:
    description: The values as JSON.
    required: true

outputs:
  values:
    description: The read values as JSON.

runs:
  using: "node16"
  main: "dist/index.js"
