name: Markdown Interpolation Action
author: Austen Stone
description: Interpolate markdown files with variables
branding:
  icon: "plus"
  color: "blue"

inputs:
  files-regex:
    description: Names of files to modify regex match.
    default: README.md
    required: false
  files-regex-flags:
    description: Regex flags for files-regex match.
    default: 'gi'
    required: false
  values:
    description: The values as JSON.
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
