name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  values:
    description: The values as JSON.
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
