name: Example 4
on:
  issues:
    types:
      - opened
      - edited

jobs:
  run:
    name: Write EXAMPLE to README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: values
        with:
          script: |
            return {
              TITLE: context.payload.issue.title,
              BODY: context.payload.issue.body,
              NUMBER: '#' + context.payload.issue.number,
            };
      - uses: ./
        with:
          values: ${{ steps.values.outputs.result }}
      - uses: stefanzweifel/git-auto-commit-action@v4
