name: Write Time to README.md
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  run:
    name: Write Time
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        id: values
        with:
          script: |
            return {
              TIME: new Date().toLocaleString('en-US', { timeZone: 'America/New_York' }),
              AUTHOR: ${{ github.actor	}},
            }
      - uses: ./
        with:
          values: ${{steps.values.outputs.result}}
      - uses: stefanzweifel/git-auto-commit-action@v4
