name: Write Time to README.md
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'A message to show in the README.md file'     
        required: true
        default: 'Hello World!'
  schedule:
    - cron: '* * * * *'

jobs:
  run:
    name: Write Time
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        id: values
        env:
          AUTHOR: ${{ github.actor	}}
          MESSAGE: ${{ github.event.inputs.message }}
        with:
          script: |
            return {
              TIME: new Date().toLocaleString('en-US', { timeZone: 'America/New_York' }),
              AUTHOR: process.env.AUTHOR,
              MESSAGE: process.env.MESSAGE
            }
      - uses: ./
        with:
          values: ${{ steps.values.outputs.result }}
      - uses: stefanzweifel/git-auto-commit-action@v4
