name: Write Time to README.md
on:
  push:
    branches:    
      - 'main'
    paths:
      - '.github/workflows/**.yml'

jobs:
  run:
    name: Write Usage to README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        id: values
        env:
          AUTHOR: ${{ github.actor	}}
          MESSAGE: ${{ github.event.inputs.message }}
        with:
          script: |
            const fs = require('fs')
            let usage = fs.readFileSync('.github/workflows/usage.yml').toString();
            usage = usage.replace('uses: ./', 'uses: austenstone/markdown-interpolation-action@master')
            return {
              USAGE: '\n```yml\n' + usage + '\n```\n'
            }
      - uses: ./
        with:
          values: ${{ steps.values.outputs.result }}
      - uses: stefanzweifel/git-auto-commit-action@v4
